### ISSUE TITLE
Add class per icon

### ISSUE THREAD

**Issue by jodzeee** [copyblogger/simple-social-icons#37]
The old version added a class to each icon, which allowed users to modify each icon separately (e.g., change background color), can that be added back?

```
<li class="social-facebook">
    <a href="http://www.facebook.com/pagename" target="_blank">...</a>
</li>
```

```
.simple-social-icons ul li.social-facebook a {
    background-color: #2C5891;
}
```

**Comment by robincornett** [comment]
I know this has been closed, but it seems to me that this change comes really close to reverting back to the original plugin markup--which seems good, but for any sites which have done extensive styling, it may break things more than otherwise. A theme which was relatively unaffected by the initial 2.0 update could experience a lot more disruption with this one. Would it be worth considering changing this to lessen potential impacts? I know why specific styling is needed on the `li` elements, but it may be less of a breaking change to do something slightly different.

**Comment by bgardner** [comment]
@robincornett Would changing classes to something like .ssi-facebook be better?

**Comment by robincornett** [comment]
I think it probably would, just because it would be totally new. In general, I'm a huge fan of 2.0, because I think it is a lot less pushy about styling, and easier to work with. I know it's hard to balance a rewrite with backwards compatibility--my feel is that doing as much as possible to "disable" old styling is actually better in this case, because the new really does work well, as long as there isn't overlap, if that makes sense.
