### ISSUE TITLE
Snapchat Icon not showing

### ISSUE THREAD

**Issue by bgardner** [copyblogger/simple-social-icons#38]
As the title states, and per below:

![snapchat](https://cloud.githubusercontent.com/assets/486261/20954162/76494526-bbfe-11e6-84de-35781380f166.jpg)

**Comment by nickcernis** [comment]
Was due to a typo: `symbol-defs.svg#social-snapshat` instead of `symbol-defs.svg#social-snapchat`.

(Introduced after our initial testing in https://github.com/copyblogger/simple-social-icons/pull/34/commits/b63f988b2328c29957b97639edf9b91d646e154e#diff-12a1b54f83ab74a5deb89c7b9c8cc7eeR158 – sorry to miss this prior to release.)
