### ISSUE TITLE
Re: "Add an additional icon in version 2.0" -- Not sure instructions are complete or maybe they are just not too clear

### ISSUE THREAD

**Issue by stormhillmedia** [copyblogger/simple-social-icons#51]
in instructions:
"plugin_dir_url(__FILE__) . 'my.svg#social-my-icon to the path of your SVG file, where social-my-icon is the ID of the icon in the SVG file, as shown below."

I am not sure where the file shown below the instructions is supposed to go. Do I add the svg image to the folder, custom folder, or what? 

This hook is about 90% useful but if this part is not more clear the whole effort is wasted and it is easier to write  my own code.

**Comment by nickcernis** [comment]
@stormhillmedia It depends where you're adding the code.

If you're adding it as a site-specific plugin (so that you don't lose custom icons even if you switch themes), `plugin_dir_url()` is correct and the SVG should go in your plugin's root directory. If you're adding it to an existing theme, you'll have to adapt the path accordingly depending so that it returns the URL of your custom SVG.

https://codex.wordpress.org/Function_Reference/get_stylesheet_directory_uri

I've added a note to the [wiki entry](https://github.com/copyblogger/simple-social-icons/wiki/Add-an-additional-icon-in-version-2.0) to that effect. If it's still not clear or you need further help with this, feel free to let me know.

**Comment by nickcernis** [comment]
I added a link in the [docs](https://github.com/copyblogger/simple-social-icons/wiki/Add-an-additional-icon-in-version-2.0) to an [example plugin](https://github.com/nickcernis/ssi-custom-icons) that shows how to add icons.
